#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$(pwd)}"
CONDA_ENV_NAME="${CONDA_ENV_NAME:-age-decoupled-surrealgan}"
PARTITION="${PARTITION:-ai}"
GPU_GRES="${GPU_GRES:-gpu:v100:1}"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"
MEMORY="${MEMORY:-32G}"
TRAIN_TIME_LIMIT="${TRAIN_TIME_LIMIT:-1-00:00:00}"
TUNE_TIME_LIMIT="${TUNE_TIME_LIMIT:-2-00:00:00}"

PROJECT_ROOT="${PROJECT_ROOT}" \
CONDA_ENV_NAME="${CONDA_ENV_NAME}" \
PARTITION="${PARTITION}" \
GPU_GRES="${GPU_GRES}" \
CPUS_PER_TASK="${CPUS_PER_TASK}" \
MEMORY="${MEMORY}" \
TIME_LIMIT="${TRAIN_TIME_LIMIT}" \
bash scripts/slurm/submit_train_scenarios.sh

PROJECT_ROOT="${PROJECT_ROOT}" \
CONDA_ENV_NAME="${CONDA_ENV_NAME}" \
PARTITION="${PARTITION}" \
GPU_GRES="${GPU_GRES}" \
CPUS_PER_TASK="${CPUS_PER_TASK}" \
MEMORY="${MEMORY}" \
TIME_LIMIT="${TUNE_TIME_LIMIT}" \
bash scripts/slurm/submit_tune_scenarios.sh
